### ISSUE TITLE
Last decoration trimmed

### ISSUE THREAD

**Issue by zakrodionov** [rubensousa/Decorator#13]
`val decoration = LinearDividerDecoration.create(color = context.getCompatColor(R.color.bg_divider),size = 16.dpToPx)  
addItemDecoration(decoration)`

It looks like the last decoration is half the height of the other

![photo_2020-12-29_10-04-44](https://user-images.githubusercontent.com/27068529/103264969-6f4e9680-49bd-11eb-8c7e-5df4206e79b2.jpg)

**Comment by rubensousa** [comment]
Released in 1.3.0

**Comment by rubensousa** [comment]
@zakrodionov let me know if it's solved for you in 1.3.0
