### ISSUE TITLE
Wrong position in DecorationLookup

### ISSUE THREAD

**Issue by zakrodionov** [rubensousa/Decorator#14]
I have a list of 3 elements, but DecorationLookup comes in positions 0-1-2-3 (four positions), I think there is an error.

**Comment by rubensousa** [comment]
Can you upload an example?

**Comment by rubensousa** [comment]
Is this happening in LinearDividerDecoration? @zakrodionov

**Comment by zakrodionov** [comment]
> Is this happening in LinearDividerDecoration? @zakrodionov

Yes, with LinearDividerDecoration

**Comment by rubensousa** [comment]
@zakrodionov Released in 1.3.0
